### ISSUE TITLE
TypeError: Cannot set property mark of #<Object> which has only a getter

### ISSUE THREAD

**Issue by mustafabayar** [inovex/scrumlr.io#3007]
I am getting the following error when I do `yarn build`:

```
TypeError: Cannot set property mark of #<Object> which has only a getter
    at Object.connectTypeScriptPerformance (/Users/m.bayar/Documents/GitHub/scrumlr.io/node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/profile/TypeScriptPerformance.js:12:36)
    at createTypeScriptReporter (/Users/m.bayar/Documents/GitHub/scrumlr.io/node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/reporter/TypeScriptReporter.js:40:49)
    at Object.<anonymous> (/Users/m.bayar/Documents/GitHub/scrumlr.io/node_modules/fork-ts-checker-webpack-plugin/lib/reporter/reporter-rpc/ReporterRpcService.js:21:30)
    at Generator.next (<anonymous>)
    at /Users/m.bayar/Documents/GitHub/scrumlr.io/node_modules/fork-ts-checker-webpack-plugin/lib/reporter/reporter-rpc/ReporterRpcService.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/m.bayar/Documents/GitHub/scrumlr.io/node_modules/fork-ts-checker-webpack-plugin/lib/reporter/reporter-rpc/ReporterRpcService.js:4:12)
    at /Users/m.bayar/Documents/GitHub/scrumlr.io/node_modules/fork-ts-checker-webpack-plugin/lib/reporter/reporter-rpc/ReporterRpcService.js:19:88
    at Object.<anonymous> (/Users/m.bayar/Documents/GitHub/scrumlr.io/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/RpcService.js:23:38)
    at Generator.next (<anonymous>)
```

Same error appears at `yarn start` as well but after a short while error log is gone and web app seems to be working locally.

But when I try to deploy it to GCP via `gcloud app deploy` command by giving the following app.yaml:
```
runtime: custom
env: flex
service: retro
```
I also see the same error log I think at the `react-scripts build` step, and when the deployment finishes, I am able to visit the Homepage via the url provided by gcloud app engine, but any other function is not working and I see the errors on the client: 
```
Homepage.errorServerConnection
Error.initApplication
Error.serverConnection
```

is this because of the TypeError I shared, or something is wrong with the way I am deploying?

Edit: I think issue with the GCP might be because of not using docker compose, but anyway as I mentioned the error log is there in local runs as well

**Comment by Schwehn42** [comment]
Hi @mustafabayar, the type error you mentioned is normal and you don't need to worry about it, but unfortunately it's something we can't do anything about at this point.  
It does seem to me that something went wrong with the deployment, as the server cannot be reached.
Did you put the correct URLs in the `.env` / `.env.development` files?   
If that's not the problem, consider posting your gcloud config (without any secrets of course), I don't know anything about that stuff, but I could pass it along, maybe someone knows something about it :)

**Comment by mustafabayar** [comment]
I think my issue is when I deploy via gcloud app deploy command, it only uses the Dockerfile in the project root and doesn't really builds the server itself. I am also not very familiar GCP, that's the issue :D 
Anyway I will investigate more about how to deploy there, thank you for the response.
